[[highlights]]
  description = 'Organise your content just using files and folders. Folders create collections and files create items.'
  svg = '<svg xmlns="http://www.w3.org/2000/svg" width="64px" height="64px" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-folder "><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path></svg>''

[[highlights]]
  description = "apple" # I am a property in fruit table/map
  svg = ""

[[highlights]]
  description = "apple" # I am a property in fruit table/map
  svg = ""

[[highlights]]
  description = "apple" # I am a property in fruit table/map
  svg = ""
